### ISSUE TITLE
What's the idea behind the custom dispatcher and if there's an built-in one?

### ISSUE THREAD

**Issue by ghost** [azasypkin/event-dispatcher#3]
It may be a very stupid question, but i'm struggling to learn... and I've no one but you.

It all begins with me trying to learn a simple something, which's: HOW CAN I CREATE A CUSTOM EVENT.

I wanted to just, for example: When a timer finishes... make a callback function for people using my script or myself to do their job. like this:

```
myTimer.addEventListener('timerFinished', function (e) {
   myDiv.html('The timer has finished.');
});
```
Since this time i'm reading all world articles and books, and i get confused... i read about observer pattern and event emitter and dispatcher: AND I FEEL LIKE ALL OF THEM ARE THE SAME THING!

And finally i get you, your code is amazing and explained very very well, i understand it and i was able to use it and achieve my goal.

But my question, and please help me to understand this, please...

What is the different between your dispatcher, other custom made dispatcher like yours and emitters. AND THIS THING:

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

They are talking about something that's built-in! built in JS called "dispatchEvent"! Like it's an official way to dispatch and create custom event, actually the article title is: 

> Creating and triggering events

Thank you for your amazing work, and i'm very sorry to bring my confusion to your time and mind.

**Comment by ghost** [comment]
If there's any books or resources  for learning this, I wish your provide my with them.

Thanks. <3

**Comment by ghost** [comment]
Check this also, i was able to achieve a custom event using the built-in dispatcher:

```
var element = document;
var event = new CustomEvent("OurSuperEvent", { detail: myData });

var myData = {
    id: 1,
    name: "An imaginary name",
    customProperty:"I need to know this string when the event is dispatched",
    moreData: [1,2,4,5,6,7]
};

element.addEventListener("OurSuperEvent", function (e) {
    console.log("The custom data of the event is : ", e.detail);
    console.log("Event is : ",e);
}, false);

setInterval(function(){ element.dispatchEvent(event); }, 1000);
```

Outputs:

```
The custom data of the event is : 
{id: 1, name: "An imaginary name", customProperty: "I need to know this string when the event is dispatched", moreData: Array(6)}

Event is :
 CustomEvent {isTrusted: false, detail: {…}, type: "OurSuperEvent", target: document, currentTarget: document, …}

```

**Comment by azasypkin** [comment]
> It may be a very stupid question, but i'm struggling to learn... and I've no one but you.

It's not a stupid question. As far as I can remember now, the main points for custom event dispatcher were:

* Restrict custom event dispatcher to a specific list of events (and throw if disallowed event name is used), so that consumers of your custom dispatcher can notice misspelled events in the code early;

* Add additional event helpers (e.g. `once` and `offAll`);

* Reduce overhead of `CustomEvent` - dispatching events through DOM has its own performance drawbacks: first you create event in Javascript and call Javascript function to pass the event, event is dispatched then to C++, and then it goes back to Javascript to call event handlers, you can easily see the difference with `JSPerf` or something;

* `Custom Events` are tied to the DOM, but this implementation was supposed to be used in DOM-less environments too (e.g Node, Service Workers etc.).

Hope this helps.
